apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: bar-ms
  name: bar-ms

spec:
  replicas: 3
  selector:
    matchLabels:
      app: bar-ms

  strategy: {}

  template:
    metadata:
      labels:
        app: bar-ms

    spec:
      containers:
      - image: foobar-bar:v1
        name: foobar-bar
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
